// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAChbtgMYdpEzWBNdr1NnYnqJAt-FEq4PE',
    appId: '1:284787433336:web:46e56d7458f1a0d031b28d',
    messagingSenderId: '284787433336',
    projectId: 'shorts-b8be6',
    authDomain: 'shorts-b8be6.firebaseapp.com',
    storageBucket: 'shorts-b8be6.firebasestorage.app',
    measurementId: 'G-K14FXGG2S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeCBA8ObhNP-hEgKb1zKCMC5sB1fQ5QhM',
    appId: '1:284787433336:android:cbee36f34e02d7ca31b28d',
    messagingSenderId: '284787433336',
    projectId: 'shorts-b8be6',
    storageBucket: 'shorts-b8be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzhaE2671xPIzleh1ZC33oiB0kjO1-UO4',
    appId: '1:284787433336:ios:c411f21fc7a3388c31b28d',
    messagingSenderId: '284787433336',
    projectId: 'shorts-b8be6',
    storageBucket: 'shorts-b8be6.firebasestorage.app',
    iosBundleId: 'com.antigravity.shortsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzhaE2671xPIzleh1ZC33oiB0kjO1-UO4',
    appId: '1:284787433336:ios:c411f21fc7a3388c31b28d',
    messagingSenderId: '284787433336',
    projectId: 'shorts-b8be6',
    storageBucket: 'shorts-b8be6.firebasestorage.app',
    iosBundleId: 'com.antigravity.shortsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAChbtgMYdpEzWBNdr1NnYnqJAt-FEq4PE',
    appId: '1:284787433336:web:af005183af350e0d31b28d',
    messagingSenderId: '284787433336',
    projectId: 'shorts-b8be6',
    authDomain: 'shorts-b8be6.firebaseapp.com',
    storageBucket: 'shorts-b8be6.firebasestorage.app',
    measurementId: 'G-84R5SLR3R4',
  );
}
